rm(list=ls())
setwd("E:\\RPI\\da")
df <- read.csv("EPI_data.csv")
head(df)
summary(df)
attach(df)
rownames(df)
colnames(df)
plot(ecdf(EPI), do.points=FALSE, verticals=TRUE) 
help('qqnorm')
par(pty='s')
qqnorm(EPI)
qqline(EPI,col=2,lwd=2)
t <- rank(EPI)/length(EPI)
q <- qnorm(t)
plot(q,EPI)
x <- seq(30,95,1)
x
qqplot(qt(ppoints(250),df=5),x,xlab = 'QQ Plot for Tang')
qqline(x)

ecdf(EPI)
plot(ecdf(EPI))
plot(ecdf(df$EPI),do.points=FALSE,verticals = TRUE) 
plot(ecdf(df$EPI),do.points=TRUE,verticals = TRUE)
x <- seq(30,95,1)
x
x2 <-seq(30,95,2)
x2
x2 <-seq(30,96,2)
x2
qqplot(qt(ppoints(250),df=5),x, xlab = "Q-Q plot")
qqline(x)
#Eploration
summary(NOX_tr)
summary(SO2_w)
shapiro.test(NOX_tr)
shapiro.test(SO2_w)
boxplot(SO2_w,NOX_tr)
fivenum(NOX_tr)
fivenum(SO2_w)
stem(NOX_tr)
stem(SO2_w)
hist(SO2_w)
rug(SO2_w)
hist(NOX_tr)
rug(NOX_tr)
hist(NOX_tr,seq(-5.,10.,1.0),prob=TRUE)

#fitting distributionS on another 2 variables
plot(ecdf(SO2_w),do.point=TRUE,verticals = TRUE)
plot(ecdf(SO2_w),do.point=FALSE,verticals = TRUE)
par(pty='s')
qqnorm(SO2_w)
qqline(SO2_w,col=2,lwd=2)

plot(ecdf(NOX_tr),do.point=TRUE,verticals = TRUE)
plot(ecdf(NOX_tr),do.point=FALSE,verticals = TRUE)
par(pty='s')
qqnorm(NOX_tr)
qqline(NOX_tr,col=2,lwd=2)

qqplot(EPI,NOX_tr)
boxplot(EPI,NOX_tr)
qqplot(EPI,SO2_w)
boxplot(EPI,SO2_w)
boxplot(SO2_w,NOX_tr)
